[package]
name = "lsctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["cargo"] }
serde = { version = "1.0.137", features = ["derive"] }
schemars = "0.8.8"
serde_json = "1.0.81"
colored = "2.0.0"