[package]
name = "lsctl"
version = "0.0.2-RC.1"
include = ["Cargo.toml", "src/**/*.rs"]
description = "CLI to help simplify my workflows"
authors = ["Luke Shay <https://github.com/lukeshay>"]
edition = "2021"
repository = "https://github.com/swc-project/swc.git"

[[bin]]
bench = false
name = "lsctl"
path = "./src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["cargo"] }
serde = { version = "1.0.137", features = ["derive"] }
schemars = "0.8.8"
serde_json = "1.0.81"
colored = "2.0.0"
toml = "0.5.9"