[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all", "--all-targets", "--all-features"]

[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--check"]

[tasks.check]
dependencies = [
  "build",
  "test-ci",
  "fmt-check",
  "clippy"
]

[tasks.version]
dependencies = ["test-ci"]
script = "./scripts/version.sh ${@}"

[tasks.tag]
dependencies = ["test-ci"]
script = "./scripts/tag.sh ${@}"

[tasks.test-rs]
command = "cargo"
args = ["test"]

[tasks.test-js]
script_runner = "@shell"
script = '''
cd npm

npm ci --no-progress --ignore-scripts

cargo run -- js config

npm run eslint
npm run prettier
npm run test -- --ci
'''

[tasks.test-ci]
dependencies = ["clean", "test-rs", "test-js"]
