name: ci

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test --verbose

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo fmt --check --verbose

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo clippy --all-targets --all-features --verbose

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: x86_64-unknown-linux-gnu
            OS: ubuntu-latest
          - TARGET: x86_64-unknown-linux-musl
            OS: ubuntu-latest
          - TARGET: aarch64-apple-darwin
            OS: macos-latest
          - TARGET: x86_64-apple-darwin
            OS: macos-latest
          - TARGET: x86_64-pc-windows-msvc
            OS: windows-latest
    needs: [test, format, clippy]
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ./target
          key: ${{ runner.os }}-${{ matrix.TARGET }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cross
        run: cargo install cross --force
      - name: Run build
        run: cross build --release --verbose --target ${{ matrix.TARGET }}
      - name: Compress (unix)
        if: startsWith(matrix.OS, 'ubuntu') || startsWith(matrix.OS, 'macos')
        run: |
          mkdir -p ./artifacts

          zip -jr9 ./artifacts/lsctl-${{ matrix.TARGET }}.zip ./target/${{ matrix.TARGET }}/release/lsctl
      - name: Compress (windows)
        if: startsWith(matrix.OS, 'windows')
        run: |
          New-Item -Path artifacts -ItemType directory

          Compress-Archive -CompressionLevel Optimal -Force -Path target/${{ matrix.TARGET }}/release/lsctl.exe -DestinationPath artifacts/lsctl-${{ matrix.TARGET }}.zip
      - name: List release files
        if: startsWith(matrix.OS, 'ubuntu') || startsWith(matrix.OS, 'macos')
        run: find ./artifacts/
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: |
            ./artifacts

  release:
    needs: build
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: result
          path: ./artifacts
      - name: List release files
        run: find ./artifacts/
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.get_version.outputs.VERSION }}
          tag_name: ${{ github.ref }}
          draft: false
          generate_release_notes: true
          files: ./artifacts/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: NPM Publish
        run: |
          cd npm
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
